application:
  title: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: ${application.title}-${application.version}
  config:
    name: ${spring.application.name}
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
      profile:  ${SPRING_PROFILE:local}