spring:
  datasource:
    url: jdbc:h2:mem:authboot;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          auto: create-drop
          import_files: sql_imports/01_role.sql,sql_imports/02_function.sql,sql_imports/03_function_type.sql,sql_imports/04_permission.sql,sql_imports/05_user.sql,sql_imports/06_assignment.sql
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  sql:
    init:
      mode: always

jwt:
  secret: YV9ncmVhdF9zdXBlcl9zZWN1cmVfYXBwbGljYXRpb25fc2VjcmV0X2Zvcl9oNTEyX2FsZ29yaXRobQ==

logging:
  level:
    org.springframework.web: INFO
    io.cmartinezs.authboot: ${LOGGING_LEVEL:DEBUG}