application:
  title: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: ${application.title}-${application.version}
  config:
    name: ${spring.application.name}
    import:
      - optional:configserver:http://localhost:8888/
      - file:./config/${SPRING_PROFILE:local}.yml
  cloud:
    config:
      fail-fast: false
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      profile:  ${SPRING_PROFILE:local}
      label: ${CONFIG_SERVER_LABEL:master}
      enabled: ${CONFIG_SERVER_ENABLED:false}