application:
  title: @project.artifactId@
  version: @project.version@

server:
  port: ${PORT:8090}

spring:
  application:
    name: @project.artifactId@
  config:
    name: ${spring.application.name}-${authboot.profile}-${authboot.version}
  profiles:
    active: ${authboot.profile}
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: false
        use_sql_comments: false
        format_sql: false
        hbm2ddl:
          auto: validate

eureka:
  client:
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    enabled: ${EUREKA_CLIENT_ENABLED:false}

logging:
  level:
    org.springframework.web: ERROR
    io.cmartinezs.authboot: ${LOGGING_LEVEL:ERROR}
  file.name: logs/${spring.config.name}.log

#start custom properties
authboot:
  error:
    notification-email: ${ERROR_NOTIFICATION_EMAIL:not.configured@mail.com}
  profile: ${SPRING_PROFILE:local}
  security-adapter:
    enable-http-basic: false
  version: @project.version@
  services:
    user:
      enabled-by-default: true

jwt:
  issuer: ${spring.application.name}
  header: ${JWT_HEADER:Authorization}
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:1800}
  secret-encoding-type: ${JWT_SECRET_ENCODING}
#end custom properties